'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Frm_Detail_Attendance_Admin
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents head As Global.HR_Attedance.Header
    
    '''<summary>
    '''My1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents My1 As Global.HR_Attedance.Menu
    
    '''<summary>
    '''lblEmployeeKey1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployeeKey1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEmployeeKey2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployeeKey2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEmployeeName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployeeName1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEmployeeName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployeeName2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEntity1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntity1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEntity2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntity2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAccessCardNo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccessCardNo1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAccessCardNo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccessCardNo2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFirstSignIn1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstSignIn1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFirstSignIn2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstSignIn2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblTimeSignIn1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTimeSignIn1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTimeSignIn2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTimeSignIn2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblTimeFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTimeFormat As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSignOut1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSignOut1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSignOut2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignOut2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblTimeSignOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTimeSignOut As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTimeSignOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTimeSignOut As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblTimeFormat2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTimeFormat2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMonth1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonth1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMonth2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonth2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDays1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDays1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDays As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTypeofDays1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTypeofDays1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTypeofDays2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTypeofDays2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblArrivalStatus1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArrivalStatus1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblArrivalStatus2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArrivalStatus2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTotalWorkingTime1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalWorkingTime1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTotalWorkingTime2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalWorkingTime2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblWorkingStatus1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWorkingStatus1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblWorkingStatus2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWorkingStatus2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblisOvertime1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblisOvertime1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblisOvertime2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblisOvertime2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOvertime1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOvertime1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOvertime2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOvertime2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LBL12Hours1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL12Hours1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LBL12Hours2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL12Hours2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''My3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents My3 As Global.HR_Attedance.Footer
End Class
